annotations:
  io.giantswarm.application.restrictions.cluster-singleton: 'true'
  io.giantswarm.application.team: honeybadger
apiVersion: v2
appVersion: v0.26.0
dependencies:
- name: flux-operator
  version: 0.26.0
  repository: oci://ghcr.io/controlplaneio-fluxcd/charts
  condition: fluxoperator.enabled
description: A Helm Chart for ControlPlane's Flux Operator.
home: https://github.com/giantswarm/flux-operator-app
icon: https://s.giantswarm.io/app-icons/flux/2/icon_light.svg
maintainers:
- name: giantswarm/team-honeybadger
  email: team-honeybadger@giantswarm.io
name: flux-operator
sources:
- https://github.com/controlplaneio-fluxcd/charts/tree/main/charts/flux-operator
version: 0.1.0
